### ISSUE TITLE
Model question

### ISSUE THREAD

**Issue by patwa67** [oxfordcontrol/COSMO.jl#154]
I just wonder if COSMO can handle a model of the form below:
```
#Toy data
A = [1.0000 0 0.5000 0.5000 0.4714 0.2357;
    0 1.0000 0.5000 0 0.2357 0.5893;
    0.5000 0 0.2500 1.0000 0.5893 0.2946;
    0.5000 0 0.2500 1.0000 0.5893 0.2946;
    0.4714 0.2357 0.5893 0.5893 1.0000 0.6111;
    0.2357 0.5893 0.5303 0.2946 0.6111 1.0000]

g = [0.5 -0.2 0.3 0.2 0.0 -0.1]
s = [1 0 1 1 0 0]
d = [0 1 0 0 1 1]
F = 0.3

#Model
max c'*g

constr c'*A*c/2 <= F
       c'*s = 0.5
       c'*d = 0.5
       c >= 0
```

**Comment by migarstka** [comment]
Hi @patwa67, 

If `A` in your model

```
#Model
max c'*g

constr c'*A*c/2 <= F
       c'*s = 0.5
       c'*d = 0.5
       c >= 0
```
is [a positive semidefinite matrix](https://en.wikipedia.org/wiki/Definite_matrix) then the problem is _convex_, and you can solve it with COSMO using a second-order-cone constraint.

Useful references: 
- [Quadratically constrained convex problems](https://en.wikipedia.org/wiki/Quadratically_constrained_quadratic_program)
- Lobo, M. S. and Vandenberghe, S. Boyd: Applications of second-order cone programming (1998)
