### ISSUE TITLE
MOI wrapper: termination_status error

### ISSUE THREAD

**Issue by ericphanson** [oxfordcontrol/COSMO.jl#77]
I don't have a MWE since I'm not sure how to get a simple model that fails in the right way, but I got the error
```julia
julia> termination_status(model)
ERROR: TypeError: in typeassert, expected MathOptInterface.TerminationStatusCode, got MathOptInterface.ResultStatusCode
```

The problem seems to be that `MOI.NO_SOLUTION` can be returned here:
https://github.com/oxfordcontrol/COSMO.jl/blob/34ebb8967cc781e4faf76ddd4130e2eade3e8f99/src/MOIWrapper.jl#L560

But `MOI.NO_SOLUTION` is a `MOI.ResultStatusCode`, and JuMP type-asserts it to be a `MOI.TerminationStatusCode`:
https://github.com/JuliaOpt/JuMP.jl/blob/fd5ea00cb602145b677c136295b07cab6791f1b0/src/JuMP.jl#L416

**Comment by migarstka** [comment]
Yes, this is a bug. 

Right now you can only get this termination code if COSMO returns `:Unsolved`. This only happens when the absolute cost value in the solver exceeds `1e20` which is usually a sign for an invalid problem or numerical problems.

From the available [MOI termination codes](http://www.juliaopt.org/MathOptInterface.jl/stable/apireference/#Termination-Status-1) nothing really fits, but I'll change it to `MOI.NUMERICAL_ERROR` .
